- name: Create gitlab directory
  ansible.builtin.file:
    path: /var/gitll
    state: directory
    owner: root
    mode: "0750"

- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: gitlab.yml.j2
    dest: /var/gitll/docker-compose.yml
    owner: root
    mode: "0750"
  notify: Run docker compose

- name: Read initial root password
  ansible.builtin.slurp:
    src: /var/gitll/config/initial_root_password
  register: gitlab_initial_password

- name: Display initial root password
  ansible.builtin.debug:
    msg: "{{ gitlab_initial_password.content | b64decode | trim }}"
