- name: Create gitlab directory
  ansible.builtin.file:
    path: /var/gitll
    state: directory
    owner: root
    mode: "0750"

- name: Create certs directory
  ansible.builtin.file:
    path: /var/gitll/certs
    state: directory
    owner: root
    mode: "0750"

- name: Install cryptography Python library ( prerequis pour private key)
  ansible.builtin.apt:
    name: python3-cryptography
    state: present
    update_cache: true

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: /var/gitll/certs/gitkc.key
    size: 2048

- name: Generate CSR
  community.crypto.openssl_csr:
    path: /var/gitll/certs/gitkc.csr
    privatekey_path: /var/gitll/certs/gitkc.key
    common_name: "*.sam.com"
    subject_alt_name:
      - "DNS:gitlab.sam.com"
      - "DNS:keycloak.sam.com"

- name: Generate self-signed certificate
  community.crypto.x509_certificate:
    path: /var/gitll/certs/gitkc.crt
    privatekey_path: /var/gitll/certs/gitkc.key
    csr_path: /var/gitll/certs/gitkc.csr
    provider: selfsigned
    selfsigned_not_after: "+3650d"

- name: Create traefik directory
  ansible.builtin.file:
    path: /var/gitll/traefik
    state: directory
    owner: root
    mode: "0750"

- name: Deploy tls.yml
  ansible.builtin.template:
    src: tls.yml.j2
    dest: /var/gitll/traefik/tls.yml
    owner: root
    mode: "0750"

- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: gitlab.yml.j2
    dest: /var/gitll/docker-compose.yml
    owner: root
    mode: "0750"
  notify: Run docker compose

- name: Flush handlers (run docker compose before reading password) # meta: flush_handlers` force l'exécution immédiate de tous les handlers en attente à cet endroit précis :
  ansible.builtin.meta: flush_handlers

- name: Read initial root password
  ansible.builtin.slurp:
    src: /var/gitll/config/initial_root_password
  register: gitlab_initial_password
  ignore_errors: true

- name: Display initial root password
  ansible.builtin.debug:
    msg: "{{ gitlab_initial_password.content | b64decode | trim }}"
  ignore_errors: true
