namespace: labkvm
name: k3scollection
version: 0.0.1
readme: README.md
authors:
  - DERKAOUI Samir
description: Collection pour déploiement K3s sur LAB KVM
license:
  - GPL-3.0-or-later
tags:
  - infrastructure
repository: https://github.com/samderkaoui/LAB_KVM
