---
- name: Check if k3s is already installed
  stat:
    path: /usr/local/bin/k3s
  register: master_cluster_k3s_binary

- name: Install k3s
  shell: set -o pipefail && curl -sfL https://get.k3s.io | sh -s - server --node-ip {{ ansible_default_ipv4.address }} --bind-address {{ ansible_default_ipv4.address }} --advertise-address {{ ansible_default_ipv4.address }}
  when: master_cluster_k3s_binary.stat.exists is false

- name: Set k3s.yaml permissions
  file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: "0777"

- name: Read k3s node token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: master_cluster_k3s_slurp_token

- name: Set k3s token as host fact
  ansible.builtin.set_fact:
    # slurp retourne le contenu du fichier encodé en base64 dans .content slurp` pour garantir un transport JSON valide quel que soit le contenu du fichier.
    # b64decode : décode le base64 pour obtenir le token en clair
    # trim : supprime le \n final présent dans le fichier node-token
    master_cluster_k3s_token: "{{ master_cluster_k3s_slurp_token.content | b64decode | trim }}"
