---
datadog_api_key: "eca6295fffd1de164a632cd2e0b88bc3"
datadog_site: "datadoghq.eu"

# Tags appliqués à toutes les métriques envoyées à Datadog
datadog_tags:
  - "project:labkvm"
  - "role:monitoring"
  - "owner:samir"
