---
# - name: Set hostname and configure VM's with right Ansible Playbook with old way ( commented main.tf in module) but might help in some
#   case so i left it there
#   hosts: all
#   become: true

#   tasks:
#     - name: Set hostname
#       hostname:
#         name: "{{ inventory_hostname }}"

#     - name: config master
#       include_tasks: ./k3s/master/master.yml
#       when: vm_hostname_by_cli == "k3s-Master"

#     - name: config worker
#       include_tasks: ./k3s/worker/worker.yml
#       when: vm_hostname_by_cli is match("k3s-Worker.*")

### SET HOSTNAME
- name: Set hostname
  hosts: all
  become: true
  tasks:
    - ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

### CONFIGURE MASTER
- name: Configure master
  hosts: masters
  become: true
  roles:
    - labkvm.k3scollection.master_cluster_k3s

### CONFIGURE WORKERS
- name: Configure workers
  hosts: workers
  become: true
  roles:
    - labkvm.k3scollection.worker_cluster_k3s

### FETCH KUBECONFIG
- name: Fetch kubeconfig from master and configure locally
  hosts: k3s-master
  become: true
  tasks:
    - name: Fetch kubeconfig from master
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env', 'HOME') }}/.kube/config"
        flat: true # Sans `flat`, Ansible reproduit le chemin complet de la source
