namespace: labkvm
name: docker
version: 0.0.1
readme: README.md
authors:
  - DERKAOUI Samir
description: Collection pour les déploiements DOCKER
license:
  - GPL-3.0-or-later
tags:
  - infrastructure
repository: https://github.com/samderkaoui/LAB_KVM
